import { PSDTemplate } from './types';

// Import local assets correctly so Vite bundles, hashes and resolves them perfectly in production/Vercel
import img1 from './assets/images/regenerated_image_1778811287349.jpg';
import img2 from './assets/images/regenerated_image_1778811290976.jpg';
import img3 from './assets/images/regenerated_image_1778811304560.jpg';
import img4 from './assets/images/regenerated_image_1778811318414.jpg';
import img5 from './assets/images/regenerated_image_1778811340170.png';

export const TEMPLATES: PSDTemplate[] = [
  {
    id: '1',
    title: 'Luxury Brand Identity Mockup',
    category: 'Branding',
    image: img1,
    gallery: [img1],
    description: 'Um mockup de identidade visual luxuoso com acabamentos em dourado e papel texturizado premium. Ideal para apresentações de logotipos corporativos de alto nível.',
    fileSize: '142 MB',
    resolution: '3000 x 4000 px',
    colors: ['#D4AF37', '#1A1A1A', '#F5F5F5', '#8E8E8E'],
  },
  {
    id: '2',
    title: 'Modelo Médico GMLab',
    category: 'Medical',
    image: img2,
    gallery: [img2],
    description: 'Template premium para clínicas de análises clínicas GMLab. Inclui layouts para consultas médicas, exames laboratoriais e check-ups completos com design institucional moderno em tons de verde esmeralda.',
    fileSize: '115 MB',
    resolution: '3000 x 4000 px',
    colors: ['#00796B', '#004D40', '#009688', '#E0F2F1'],
  },
  {
    id: '3',
    title: 'Maquete de vestuário streetwear',
    category: 'Fashion',
    image: img3,
    gallery: [img3],
    description: 'Mockup de vestuário streetwear premium, incluindo hoodies e t-shirts de alta qualidade com texturas de tecido realistas.',
    fileSize: '215 MB',
    resolution: '4000 x 5000 px',
    colors: ['#000000', '#FFFFFF', '#7B7B7B', '#4A4A4A'],
  },
  {
    id: '4',
    title: 'Modern App UI Presentation',
    category: 'Digital',
    image: img4,
    gallery: [img4],
    description: 'Template de apresentação de interface de aplicativo móvel moderno, com efeitos de profundidade e sombras dinâmicas.',
    fileSize: '128 MB',
    resolution: '3000 x 2000 px',
    colors: ['#6366F1', '#A855F7', '#1E1B4B', '#F8FAFC'],
  },
  {
    id: '5',
    title: 'Cosmetic Packaging Mockup',
    category: 'Packaging',
    image: img5,
    gallery: [img5],
    description: 'Mockup de embalagem de cosméticos de alta fidelidade com reflexos realistas e texturas de vidro.',
    fileSize: '185 MB',
    resolution: '3500 x 3500 px',
    colors: ['#FADADD', '#FFFFFF', '#000000', '#C0C0C0'],
  },
  {
    id: '6',
    title: 'Editorial Magazine Layout',
    category: 'Print',
    image: img1,
    gallery: [img1],
    description: 'Layout de revista editorial contemporânea com grid flexível e tipografia elegante.',
    fileSize: '156 MB',
    resolution: '2480 x 3508 px',
    colors: ['#000000', '#FFFFFF', '#FF0000', '#F2F2F2'],
  },
  {
    id: '7',
    title: 'Maquete de Cartão de Visita Vol. 1',
    category: 'Stationery',
    image: img2,
    gallery: [img2],
    description: 'Mockup de cartões de visita minimalistas empilhados para uma apresentação profissional.',
    fileSize: '65 MB',
    resolution: '2000 x 1500 px',
    colors: ['#FFFFFF', '#000000', '#888888'],
  },
  {
    id: '8',
    title: 'Social Media Feed Kit',
    category: 'Digital',
    image: img3,
    gallery: [img3],
    description: 'Kit de posts para redes sociais com design coeso e moderno.',
    fileSize: '110 MB',
    resolution: '1080 x 1080 px',
    colors: ['#E1306C', '#F56040', '#FCAF45'],
  },
  {
    id: '9',
    title: 'Real Estate Brochure',
    category: 'Print',
    image: img4,
    gallery: [img4],
    description: 'Brochura imobiliária de luxo com layouts limpos e elegantes.',
    fileSize: '230 MB',
    resolution: 'A4 300 DPI',
    colors: ['#2F3E46', '#CAD2C5', '#84A98C'],
  },
  {
    id: '10',
    title: 'Coffee Shop Branding',
    category: 'Branding',
    image: img5,
    gallery: [img5],
    description: 'Design de identidade completo para cafeterias artesanais.',
    fileSize: '145 MB',
    resolution: '3000 x 3000 px',
    colors: ['#4B3832', '#3C2F2F', '#BE9B7B'],
  },
  {
    id: '11',
    title: 'Gaming Twitch Overlay',
    category: 'Digital',
    image: img1,
    gallery: [img1],
    description: 'Overlay dinâmico para streamers com estética gamer moderna.',
    fileSize: '88 MB',
    resolution: '1920 x 1080 px',
    colors: ['#9146FF', '#000000', '#FFFFFF'],
  },
  {
    id: '12',
    title: 'Vintage Vinyl Cover',
    category: 'Abstract',
    image: img2,
    gallery: [img2],
    description: 'Capa de disco de vinil vintage com texturas de papel envelhecido.',
    fileSize: '167 MB',
    resolution: '3000 x 3000 px',
    colors: ['#A0522D', '#DEB887', '#F5F5DC'],
  }
];
